---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.TrustedSandbox: "false"
    io.kubernetes.cri.untrusted-workload: "true"
  name: nginx-untrusted-crio
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    container-runtime: "cri-o" 
    kata-runtime: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-trusted
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    kata-runtime: "true"
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.TrustedSandbox: "false"
    io.kubernetes.cri.untrusted-workload: "true"
  name: nginx-untrusted-containerd
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    container-runtime: "containerd" 
    kata-runtime: "true"
