---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kata-label-node
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-labeler
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kata-label-node-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-labeler
subjects:
- kind: ServiceAccount
  name: kata-label-node
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubelet-runtime-labeler
  namespace: kube-system
spec:
  selector:
      matchLabels:
        name: kubelet-runtime-labeler
  template:
    metadata:
        labels:
          name: kubelet-runtime-labeler
    spec:
      serviceAccountName: kata-label-node
      containers:
      - name: kubelet-runtime-labeler-pod
        image: egernst/kata-deploy
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "kubectl label node $NODE_NAME container-runtime-"]
        command: [ "sh", "-c" ]
        args:
        - printenv NODE_NAME;
          kubectl get node $NODE_NAME --show-labels;
          kubectl label node $NODE_NAME container-runtime=$(kubectl describe node $NODE_NAME | awk -F'[:]' '/Container Runtime Version/ {print $2}' |  tr -d ' ');
          kubectl get node $NODE_NAME --show-labels;
          while true;
          do sleep 30; done;
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: false
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
